In [70]:
import numpy as np

In [71]:
# Define input data
input_data = np.array([0.8, 0.2, 0.5])
input_size=3

In [72]:
# Define weights and bias for the perceptron
weights = np.random.rand(3)
bias = np.random.rand()

In [73]:
print("weights : ",weights )
print("bias : ", bias)

weights :  [0.85947439 0.96380995 0.66679359]
bias :  0.3805626327076491


In [74]:
# Calculating the weighted sum of inputs and add bias
Sum_weights = np.dot(input_data,weights) + bias
print("Before Activation Sum of Weights is : ",Sum_weights)

Before Activation Sum of Weights is :  1.5943009298838442


In [75]:
# Define the activation function (in this case, a step function)
def activation_function(x):
    threshold = 50.0 
    return 1 if x > threshold else 0

In [76]:
# Perform forward propagation
# weighted_sum = np.dot(input_data, weights) + bias
# print(weighted_sum)
output = activation_function(Sum_weights)

In [77]:
print("Output of the perceptron:", output)

Output of the perceptron: 0


In [78]:
# Sigmoid function
def Sigmoid_Function(x):
    return 1/ (1 + np.exp(-x))

In [79]:
output = Sigmoid_Function(Sum_weights)
print("Sigmoid Activation Function Output:", output)

Sigmoid Activation Function Output: 0.8312203536118633


Multilayer Neuro Network 

In [80]:
M_input_data = np.array([0.5,2.5,5.5])

R_weights = np.random.rand(3,3)  # 3Layers and nuerons
R_bias = np.random.randint(1,101 , size=3)

In [81]:
print("Randomly Generated Weights:\n", R_weights)
print("Randomly Generated Biases:", R_bias)

Randomly Generated Weights:
 [[0.58656101 0.69439771 0.66453198]
 [0.20238962 0.08113743 0.14029306]
 [0.59121938 0.71208879 0.17595166]]
Randomly Generated Biases: [59 94 82]


In [82]:
# Calculating the weighted sum of inputs and add bias
Sum_of_weights = np.dot(M_input_data,R_weights)+ R_bias
print("Before Activation Sum of Weights is : ",Sum_of_weights)

Before Activation Sum of Weights is :  [63.05096116 98.46653076 83.65073278]


In [83]:
# using activation function
def activation_function(val):
    threshold = 50.0
    return np.where(val > threshold, 1, 0)
Output = activation_function(Sum_of_weights)
print("Output of the perceptron:", Output)

Output of the perceptron: [1 1 1]


In [84]:
# Sigmoid Activation Functions 
Sigmoid_Output = Sigmoid_Function(Sum_of_weights)
print("Sigmoid Activation Function Output For Input Layer:", Sigmoid_Output)

Sigmoid Activation Function Output For Input Layer: [1. 1. 1.]


Hidden layers 

in which Sigmoid Output become an input for nexr layer

In [85]:
H_weights = np.random.rand(3,3)  # 3Layers and nuerons
H_bias = np.random.randint(1,101 , size=3)


print("Randomly Generated Weights:\n", H_weights)
print("Randomly Generated Biases:", H_bias)

Randomly Generated Weights:
 [[0.62351644 0.00286539 0.79605547]
 [0.07330689 0.88590194 0.38177469]
 [0.49235247 0.13103564 0.90714433]]
Randomly Generated Biases: [40 65  3]


In [86]:
# Calculating the weighted sum of inputs and add bias
Sum_H_weights = np.dot(Sigmoid_Output,H_weights)+ H_bias
print("Before Activation Sum of Weights is : ",Sum_H_weights)

Before Activation Sum of Weights is :  [41.1891758  66.01980298  5.08497449]


In [87]:
# Activation Fucntion
H_Activation_Output = activation_function(Sum_H_weights)
print("Output of the perceptron:", H_Activation_Output)

Output of the perceptron: [0 1 0]


In [88]:
# Sigmoid Activation Functions 
H_Sigmoid_Output = Sigmoid_Function(Sum_H_weights)
print("Sigmoid Activation Function Output For Input Layer:", H_Sigmoid_Output)

Sigmoid Activation Function Output For Input Layer: [1.         1.         0.99384902]


Final Single Neuron output 

In [94]:
F_input_data = np.array([0.5,2.5,5.5])

F_weights = np.random.rand(3)  # 3Layers and nuerons
F_bias = np.random.randint(1,101)


print("Randomly Generated Weights:\n", F_weights)
print("Randomly Generated Biases:", F_bias)

Randomly Generated Weights:
 [0.01442831 0.82114503 0.13784612]
Randomly Generated Biases: 88


In [95]:
# Calculating the weighted sum of inputs and add bias
Sum_F_weights = np.dot(H_Sigmoid_Output,F_weights)+ F_bias
print("Before Activation Sum of Weights is : ",Sum_F_weights)

Before Activation Sum of Weights is :  88.97257157509489


In [96]:
# Activation Fucntion
F_Activation_Output = activation_function(Sum_F_weights)
print("Output of the perceptron:", F_Activation_Output)

Output of the perceptron: 1


In [97]:
# Sigmoid Activation Functions 
F_Sigmoid_Output = Sigmoid_Function(Sum_F_weights)
print("Sigmoid Activation Function Output For Input Layer:", F_Sigmoid_Output)

Sigmoid Activation Function Output For Input Layer: 1.0
