In [35]:
# Libraries
import pandas as pd
import numpy as np 


In [36]:
# importing dataset 
data = pd.read_csv("data.csv")

In [37]:
data.head()

acidity  sugar  density   pH  wine_quality
0      7.8   12.3    1.002  3.4             1
1      6.5    8.9    1.010  3.1             0
2      8.2   15.2    0.995  3.5             1
3      5.5    5.1    1.015  3.2             0
4      7.1   10.6    1.000  3.7             1

Features Saparating 

In [38]:
Columns = ['acidity', 'sugar', 'density', 'pH']

In [39]:
x = data[Columns]

In [40]:
y = data['wine_quality']

Layer 1 

In [41]:
 # create function of Sigmoid
def Sigmoid(x):
    return 1/(1 + np.exp(-x))

In [42]:
# Binary cross-entropy loss
def binary_crossentropy(y_true, y_pred):
    epsilon = 1e-15  # Avoid division by zero
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return -(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

In [43]:
weight1 = np.random.rand(4, 4) # Change the shape (4, 4) as needed
weigiaseht1 = weight1*0.01
biase1 = np.random.randint(1, 101, size=4)
biase1 = biase1* 0.01

In [44]:
Sum = np.dot(x, weight1) + biase1
Sig_Fun = Sigmoid(Sum)
print("Output: ",Sig_Fun)

Output:  [[0.99999796 0.99999997 0.99999926 0.99999948]
 [0.99997375 0.99999893 0.99998128 0.99999097]
 [0.99999956 1.         0.99999995 0.99999994]
 [0.99972168 0.99996591 0.99947613 0.99986458]
 [0.99999321 0.99999985 0.99999722 0.99999847]
 [0.99996971 0.99999834 0.99994708 0.99998197]
 [0.99999905 0.99999999 0.9999998  0.99999984]
 [0.99998826 0.99999961 0.99998857 0.99999523]
 [0.99999627 0.99999993 0.99999811 0.99999898]
 [0.99991542 0.99999305 0.9998305  0.99995008]
 [0.99999963 1.         0.99999994 0.99999994]
 [0.99970577 0.9999541  0.99876239 0.99976577]
 [0.99999489 0.99999989 0.99999736 0.99999857]
 [0.99997126 0.99999863 0.99996734 0.9999876 ]
 [0.99999983 1.         0.99999998 0.99999998]
 [0.99992342 0.99999476 0.9999079  0.99997048]
 [0.99999843 0.99999998 0.99999951 0.99999965]
 [0.99995717 0.99999745 0.99993494 0.99997794]
 [0.99999947 1.         0.99999989 0.9999999 ]
 [0.99997894 0.99999915 0.99998039 0.99999196]]


Layer 2

In [45]:
weight2 = np.random.rand(4, 4) # Change the shape (4, 4) as needed
weight2 = weight2*0.01
biase2 = np.random.randint(1, 101, size=4)
biase2 = biase2* 0.01

In [46]:
Sum2 = np.dot(Sig_Fun, weight2) + biase2
Sig_Fun2 = Sigmoid(Sum2)
print("Output: ",Sig_Fun2)

Output:  [[0.5389151  0.62573725 0.58042094 0.70789848]
 [0.53891503 0.62573718 0.58042087 0.70789843]
 [0.5389151  0.62573725 0.58042095 0.70789848]
 [0.53891369 0.62573578 0.58042004 0.70789776]
 [0.53891509 0.62573724 0.58042093 0.70789847]
 [0.53891495 0.6257371  0.58042085 0.70789841]
 [0.5389151  0.62573725 0.58042094 0.70789848]
 [0.53891506 0.62573721 0.58042091 0.70789846]
 [0.53891509 0.62573724 0.58042094 0.70789848]
 [0.53891465 0.62573679 0.58042066 0.70789826]
 [0.5389151  0.62573725 0.58042095 0.70789848]
 [0.53891234 0.62573423 0.58041966 0.70789732]
 [0.53891509 0.62573724 0.58042093 0.70789847]
 [0.538915   0.62573715 0.58042086 0.70789842]
 [0.5389151  0.62573725 0.58042095 0.70789848]
 [0.53891481 0.62573697 0.58042072 0.70789832]
 [0.5389151  0.62573725 0.58042094 0.70789848]
 [0.53891491 0.62573706 0.58042081 0.70789838]
 [0.5389151  0.62573725 0.58042094 0.70789848]
 [0.53891503 0.62573718 0.58042089 0.70789844]]


Layer 3

In [47]:
weight3 = np.random.rand(4) # Change the shape (4) as needed
weight3 = weight3*0.01
biase3 = np.random.randint(1, 101)
biase3 = biase3* 0.01

In [48]:
Sum3 = np.dot(Sig_Fun2, weight3) + biase3
Sig_Fun3 = Sigmoid(Sum3)
loss = np.mean(binary_crossentropy(y, Sig_Fun3))
print("Output: ",Sig_Fun3)

Output:  [0.61786719 0.61786719 0.61786719 0.61786719 0.61786719 0.61786719
 0.61786719 0.61786719 0.61786719 0.61786719 0.61786719 0.61786718
 0.61786719 0.61786719 0.61786719 0.61786719 0.61786719 0.61786719
 0.61786719 0.61786719]


Calculating Loss 

In [49]:
# Calculate loss row-wise after Layer 3
row_loss = np.array([binary_crossentropy(true_label, predicted_label) for true_label, predicted_label in zip(y, Sig_Fun3)])

In [50]:
print(row_loss)

[0.48148175 0.96198706 0.48148175 0.96198705 0.48148175 0.96198706
 0.48148175 0.96198706 0.48148175 0.96198706 0.48148175 0.96198704
 0.48148175 0.96198706 0.48148175 0.96198706 0.48148175 0.96198706
 0.48148175 0.96198706]


In [51]:
# Calculating Loss for total dataset
print("Loss: ",loss)

Loss:  0.7217344023000881
